blog/blog/BlogApp/urls.py
from django.urls import path,include
from . import views
from BlogApp.views import IndexView, PostListView, PostDetailView, PostCreateView,PostUpdateView, PostDeleteView, LandingView

app_name = 'BlogApp'

urlpatterns = [
    path('', LandingView.as_view(), name='Landing'),
    path('home/', IndexView.as_view(), name='Index'),
    path('post/<int:pk>/', PostDetailView.as_view(), name='Post-detail'),
    path('chapters/new/', PostCreateView.as_view(), name='Post-create'),
    path('chapters/', PostListView.as_view() , name='Blogs'),
    path('post/<int:pk>/update/', PostUpdateView.as_view(), name='Post-update'),
    path('post/<int:pk>/delete/', PostDeleteView.as_view(), name='Post-delete'),
]

blog/blog/blog/urls.py
from django.contrib import admin
from django.urls import path, include
from users import views as user_views
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static




urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("BlogApp.urls", namespace="Blog")),
    path('', include("users.urls", namespace="users"))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/blog/users/urls.py
from django.urls import path,include
from . import views
from users import views as user_views
from django.contrib.auth import views as auth_views



app_name = 'users'

urlpatterns = [
    path('register/', user_views.Register , name='Register'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html') , name='Login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html') , name='Logout'),
    path('profile/', user_views.Profile , name='Profile')
]

blog/blog/BlogApp/models.py
from django.db import models
from  django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse

class BlogPost(models.Model):
    title = models.CharField(max_length = 40)
    content = models.CharField(max_length=5000,  null=True)
    date_posted = models.DateField(default=timezone.now)
    author = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.title


    def get_absolute_url(self):
        return reverse('Blog:Index')

        # kwargs={'pk':self.pk})

class Comment(models.Model):
    post = models.ForeignKey(BlogPost, on_delete=models.CASCADE)
    comment = models.CharField(max_length = 200)
    author = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.comment

    def get_absolute_url(self):
        return reverse('Blog:Post-detail',kwargs={'pk':self.post.pk})

blog/blog/BlogApp/views.py
from django.shortcuts import render, redirect
from django.views.generic.base import TemplateView
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from .models import BlogPost, Comment
from users.models import Profile
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
import datetime
# Create your views here.


# view of the landingspage
class LandingView(TemplateView):
    template_name = "BlogApp/landing.html"

    def get_context_data(self, *args, **kwargs):
        context = super(LandingView, self).get_context_data(*args, **kwargs)
        context['time'] = datetime.datetime.now()
        return context

class IndexView(ListView):
    model = BlogPost
    context_object_name = 'posts'
    template_name = "BlogApp/index.html"
    ordering = ['-date_posted']

    def get_queryset(self):
        if self.request.user.is_authenticated:
            queryset =  BlogPost.objects.filter(author__exact=self.request.user)
            return queryset

    def get_context_data(self, *args, **kwargs):
        context = super(IndexView, self).get_context_data(*args, **kwargs)
        context['time'] = datetime.datetime.now()
        return context



class PostListView(ListView):
    model = BlogPost
    context_object_name = 'posts'
    template_name = "BlogApp/blogs.html"
    ordering = ['-date_posted']



class PostDetailView(LoginRequiredMixin, CreateView):
    login_url = '/login/'
    model = Comment
    template_name = "BlogApp/post_detail.html"
    fields = ['comment']


    def get_context_data(self, *args, **kwargs):
        context = super(PostDetailView, self).get_context_data(**kwargs)
        context['posted'] = BlogPost.objects.get(id=self.kwargs['pk'])
        context['comments'] = Comment.objects.filter(post__exact=context['posted'])
        return context


    def form_valid(self, form,  *args, **kwargs):
        context = super(PostDetailView, self).get_context_data(**kwargs)
        obj = form.save(commit=False)
        obj.author = self.request.user
        obj.post = BlogPost.objects.get(id=self.kwargs['pk'])
        obj.save()
        return super().form_valid(form)



class PostCreateView(LoginRequiredMixin, CreateView):
    login_url = '/login/'
    model = BlogPost
    template_name = "BlogApp/post_form.html"
    fields = ['title', 'content']

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)



class PostDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = BlogPost
    template_name = "BlogApp/post_confirm_delete.html"
    success_url = "/home/"

    def test_func(self):
        post = self.get_object()

        if self.request.user == post.author:
            return True
        return False


class PostUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    login_url = '/login/'
    model = BlogPost
    template_name = "BlogApp/post_form.html"
    fields = ['title', 'content']

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

    def test_func(self):
        post = self.get_object()

        if self.request.user == post.author:
            return True
        return False

blog/blog/BlogApp/templates/BlogApp/blogs.html
{% extends 'BlogApp/layout.html' %} {% load static %} {% block content %}
<head>
    <link type="text/css" href="{% static 'BlogApp/css/sidenav.css' %}" rel="stylesheet">
    <link type="text/css" href="{% static 'BlogApp/css/index.css' %}" rel="stylesheet">
</head>

{% if user.is_authenticated %}
<!-- Page Content -->
<div class="container-fluid" >
    <div class="row">
        <div class="col-lg-4 col-md-12 col-sm-12 backnav">
            <div class="row">
                <div class="col-lg-6 col-md-6 col-sm-6">
                    <div class="card">
                        <img class="card-img-top  img-responsive" src="{{ user.profile.image.url }}" alt="Card image cap">
                        <div class="card-body">
                            <h5 class="card-title"> Hello {{user.username}}</h5>
                            <p class="card-text">Click here to update or view your profile</p>
                            <div class="text-center">
                                <a class='text-center' href="{% url 'users:Profile' %}">
                                <button class="btn btn-secondary" type="button">Update your profiles</button>
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-6 col-md-6 col-sm-6 ">
                    <div class="card">
                        <img class="card-img-top  img-responsive" src="{% static 'BlogApp/Images/notebook.jpg' %}" alt="Card image cap">
                        <div class="card-body">
                            <h5 class="card-title">Chapter</h5>
                            <p class="card-text">Click here to Create a new Chapter</p>
                            <div class="text-center">
                                <a href="{% url 'BlogApp:Post-create' %}">
                                <button class="btn btn-secondary" type="button">Create new Chapter</button>
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-6 col-md-6 col-sm-6">
                    <div class="card">
                        <img class="card-img-top  img-responsive" src="{% static 'BlogApp/Images/reading.jpg'  %}" alt="Card image cap">
                        <div class="card-body">
                            <h5 class="card-title">Read other Chapters </h5>
                            <p class="card-text">Click here to see what other people have posted</p>
                            <div class="text-center">
                                <a href="{% url 'BlogApp:Blogs' %}">
                                <button class="btn btn-secondary" type="button">Click here</button>
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-6 col-md-6 col-sm-6 ">
                    <div class="card">
                        <img class="card-img-top img-responsive" src="{% static 'BlogApp/Images/books.jpg' %}" alt="Card image cap">
                        <div class="card-body">
                            <h5 class="card-title">Journals</h5>
                            <p class="card-text">Click here to see your own journal</p>
                            <div class="text-center">
                                <a href="{% url 'BlogApp:Index' %}">
                                <button class="btn btn-secondary" type="button">Go to your journal</button>
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-lg-8 col-md-12 col-sm-12 content-style">
            <div class="text-center">
                <h1>Hello {{request.user.username}}</h1>
                <h4> See what other people have posted</h4>
            </div>
            {% for post in posts %}
            <div class="journal-block-title">
                <h5 class="text-center"> {{ post.author}} <i>{{ post.date_posted }} </i>  <a href= "{% url 'BlogApp:Post-detail' post.id %}"> Click to Comment</a> </h5>
                <h5>{{post.title}} </h5>
            </div>
            <div class="journal-block-content">
                <p class="text-justify" >{{post.content}}</p>
            </div>
            {% endfor %}
        </div>
    </div>
    <!-- /.row -->
</div>
<!-- /.container -->
{% else %}
<div class="background-image">
    <div class="container">
				<div class="no-acces">
            <h2>Sorry you have no acces to this page.</h2>
				</div>
				<div class="journal-block-content">
                <a href=" {% url 'users:Login' %}">
                <button type="button" class="btn btn-dark btn-lg">Login</button>
                </a> or
                <a href=" {% url 'users:Register' %}">
                <button type="button" class="btn btn-dark btn-lg">Register</button>
                </a>
            </div>
        </div>
    </div>
{% endif %} {% endblock %}

blog/blog/BlogApp/templates/BlogApp/index.html
{% extends 'BlogApp/layout.html' %} {% load static %} {% block content %}
<head>
    <link type="text/css" href="{% static 'BlogApp/css/Index.css' %}" rel="stylesheet">
    <link type="text/css" href="{% static 'BlogApp/css/sidenav.css' %}" rel="stylesheet">
</head>
{% if user.is_authenticated %}
<div class="container-fluid">
<div class="row">
    <div class="col-lg-4 col-md-12 col-sm-12 backnav">
        <div class="row">
            <div class="col-lg-6 col-md-6 col-sm-6">
                <div class="card">
                    <img class="card-img-top  img-responsive" src="{{ user.profile.image.url }}" alt="Card image cap">
                    <div class="card-body">
                        <h5 class="card-title"> Hello {{user.username}}</h5>
                        <p class="card-text">Click here to update or view your profile</p>
                        <div class="text-center">
                            <a class='text-center' href="{% url 'users:Profile' %}">
                            <button class="btn btn-secondary" type="button">Update your profiles</button>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-6 col-md-6 col-sm-6 ">
                <div class="card">
                    <img class="card-img-top  img-responsive" src="{% static 'BlogApp/Images/notebook.jpg' %}" alt="Card image cap">
                    <div class="card-body">
                        <h5 class="card-title">Chapter</h5>
                        <p class="card-text">Click here to create and share a new Chapter</p>
                        <div class="text-center">
                            <a href="{% url 'BlogApp:Post-create' %}">
                            <button class="btn btn-secondary" type="button">Create new Chapter</button>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-6 col-md-6 col-sm-6">
                <div class="card">
                    <img class="card-img-top  img-responsive" src="{% static 'BlogApp/Images/reading.jpg'  %}" alt="Card image cap">
                    <div class="card-body">
                        <h5 class="card-title">Read other Chapters </h5>
                        <p class="card-text">Click here to see what other people have posted</p>
                        <div class="text-center">
                            <a href="{% url 'BlogApp:Blogs' %}">
                            <button class="btn btn-secondary" type="button">Click here</button>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-6 col-md-6 col-sm-6 ">
                <div class="card">
                    <img class="card-img-top img-responsive" src="{% static 'BlogApp/Images/books.jpg' %}" alt="Card image cap">
                    <div class="card-body">
                        <h5 class="card-title">Journals</h5>
                        <p class="card-text">Click here to see your own journal</p>
                        <div class="text-center">
                            <a href="{% url 'BlogApp:Index' %}">
                            <button class="btn btn-secondary" type="button">Go to your journal</button>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% if posts %}
    <div class="col-lg-8 col-md-12 col-sm-12">
        <div class="post-block">
            <h2 style="text-align: center; margin-bottom: 45px;">Your Previous Journals: </h2>
            {% for post in posts %}
            <div class="journal-block-title">
                <h5>{{post.title}}<br> <i>{{post.date_posted}}</i></h5>
                <a href="{% url 'Blog:Post-update' post.id %}"><button >Update</button></a>
                <a href="{% url 'Blog:Post-delete' post.id %}"><button >Delete</button></a>
            </div>
            <hr>
            <div class="journal-block-content">
                <p class="text-justify" >{{post.content}}</p>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
{% else %}
<div style="margin-bottom: 45px;" class="container">
    <div class="journal-block-title post-block">
        <h5>You have no journals!</h5>
        <a href="{% url 'BlogApp:Post-create' %}">
        <button class="btn btn-secondary" type="button">Create Journal</button>
        </a>
    </div>
</div>
{% endif%}
{% else %}
<div class="background-image">
    <div class="container">
        <div class="no-acces ">
            <h3> Login to create a journal</h3>
        </div>
        <div class="journal-block-content">
            <a href="{% url 'users:Login' %}">
            <button class="btn btn-dark btn-lg" type="button" name="button">Click to log in</button>
            </a>or
            <a href="{% url 'users:Register' %}">
            <button class="btn btn-dark btn-lg" type="button" name="button">Create an account</button>
            </a>
        </div>
    </div>
</div>
{% endif%}
{% endblock %}

blog/blog/BlogApp/templates/BlogApp/landing.html
{% load static %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
    <head>
        <meta charset="utf-8">
        <title> Caspers Compound</title>
        <link href='https://fonts.googleapis.com/css?family=Archivo' rel='stylesheet'>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
        <link type="text/css" href="{% static 'BlogApp/css/landing.css' %}" rel="stylesheet">
    </head>
    <body>
        <!-- Navigation -->
        <div class="container-fluid">
            <nav class="navbar navbar-expand-sm navbar-dark bg-dark fixed-top">
                <div class="container">
                    <a class="navbar-brand fixed" href="{% url 'Blog:Index' %}">
                    <img src="{% static 'BlogApp/Images/Brand_logo.png' %}" width="80" height="60" class="d-inline-block align-top" alt=""></a>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse" id="navbarResponsive">
                        <ul class="navbar-nav ml-auto">
                            <li class="nav-item active">
                                <a class="nav-link" href="{% url 'Blog:Index' %}">Home
                                <span class="sr-only">(current)</span>
                                </a>
                            </li>
                            <li class="nav-item active">
                                <a class="nav-link" href="{% url 'Blog:Blogs' %}">Journals</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'users:Login' %}">Login</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'users:Register' %}">Register</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </nav>
        </div>
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div id="content">
                        <h1>Caspers Compound</h1>
                        {% if request.user.username %}
                        <p>Hello {{request.user.username}}
                            <br>Today is {{ time }}
                            <br>The perfect time to write what's on your mind
                        </p>
                        {% else %}
                        <h3> Start Writing Your Journals</h3>
                        {% endif %}
                        <hr>
                        <a href="{% url  'Blog:Index' %}"><button class="btn bg-white tn-default btn-lg"> Get Started</button></a>
                    </div>
                </div>
            </div>
        </div>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
    </body>
</html>

blog/blog/BlogApp/templates/BlogApp/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>Caspers Compound</title>
    <link href='https://fonts.googleapis.com/css?family=Archivo' rel='stylesheet'>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
    <link type="text/css" href="{% static 'BlogApp/css/Layout.css' %}" rel="stylesheet">
</head>
<body>

    <!-- Navigation -->
    <div class="container-fluid">
        <nav class="navbar navbar-expand-sm navbar-dark bg-dark fixed-top">
            <div class="container">
                <a class="navbar-brand fixed" href="{% url 'Blog:Index' %}">
                <img src="{% static 'BlogApp/Images/Brand_logo.png' %}" width="80" height="60" class="d-inline-block align-top" alt=""></a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item active">
                            <a class="nav-link" href="{% url 'Blog:Index' %}">Home
                                <span class="sr-only">(current)</span>
                            </a>
                        </li>
                        <li class="nav-item active">
                            <a class="nav-link" href="{% url 'Blog:Blogs' %}">Chapters</a>
                        </li>
                        {% if user.is_authenticated %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'users:Profile' %}">Profile</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'users:Logout' %}">Logout</a>
                        </li>
                        {% else %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'users:Login' %}">Login</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'users:Register' %}">Register</a>
                        </li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </nav>
    </div>
    {% if messages %}
       {% for message in messages%}
       <div class="alert alert-{{ message.tags}}">
         {{message}}
       </div>
       {% endfor%}
    {% endif %}

    <div class="content-block">

    </div>


    {% block content %} {% endblock %}

    <!-- <div class="footer container-fluid">
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-bottom">
      <p> Copyright &copy; <script> document.write(new Date().getFullYear()); </script> </p>
          </nav>
    </div> -->

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>

</body>

</html>

blog/blog/BlogApp/templates/BlogApp/post_detail.html
{% extends 'BlogApp/layout.html' %} {% load static %} {% block content %} {% if user.is_authenticated %} {% load crispy_forms_tags %}
<div class="container" style="margin-top: 100px">
<div class="row">
<div class="col-lg-8">
<h1> Post</h1>
<a href="{%url 'Blog:Blogs'%}">
<button class="btn btn-primary" type="button" name="button"> Back to Journals</button>
</a>
<div class="card my-4">
    <h5 class="card-header">  {{ posted.author}}  {{posted.title}} <i>{{ posted.date_posted }} </i></h5>
    {% if posted.author == user %}
    <a class="btn btn-secondary" href="{% url 'Blog:Post-update' posted.id %}"> Update post </a>
    <a class="btn btn-danger" href="{% url 'Blog:Post-delete' posted.id %}"> Delete Post</a> {% endif %}
    <div class="card-body">
        {{ posted.content}}
    </div>
</div>
{% else %}
<div class="container">
    <div class="card my-4">
        <h5 class="card-header">Sorry no acces</h5>
        <div class="card-body">
            <h2>Sorry you have no acces to this page.</h2>
            <a href=" {% url 'users:Login' %}">
            <button type="button" class="btn btn-secondary">Login</button>
            </a>
            <a href=" {% url 'users:Register' %}">
            <button type="button" class="btn btn-secondary">Register</button>
            </a>
        </div>
    </div>
</div>
{% endif %}
<div class="card my-4">
    <h5 class="card-header">Leave a Comment:</h5>
    <div class="card-body">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                {{form|crispy }}
            </fieldset>
            <div class="form-group">
                <button type="submit" class="btn btn-outline-info"> Post comment</button>
            </div>
        </form>
    </div>
</div>
<!-- Single Comment -->
{% for item in comments %}
<div class="media mb-4">
    <img class="d-flex mr-3 rounded-circle" src="{}" alt="">
    <div class="media-body">
        <h5 class="mt-0">{{item.author}}</h5>
        {{ item.comment}}
    </div>
</div>
{% endfor %}
{% endblock %}

blog/blog/BlogApp/templates/BlogApp/post_form.html
{% extends 'BlogApp/layout.html' %} {% load static %} {% block content %} {% load crispy_forms_tags %} {% load widget_tweaks %}
<head>
    <link type="text/css" href="{% static 'BlogApp/css/sidenav.css' %}" rel="stylesheet">
</head>
<div class="container-fluid">
    <div class="row">
        <div class="col-lg-4 col-md-12 col-sm-12 backnav">
            <div class="row">
                <div class="col-lg-6 col-md-6 col-sm-6">
                    <div class="card">
                        <img class="card-img-top  img-responsive" src="{{ user.profile.image.url }}" alt="Card image cap">
                        <div class="card-body">
                            <h5 class="card-title"> Hello {{user.username}}</h5>
                            <p class="card-text">Click here to update or view your profile</p>
                            <div class="text-center">
                                <a class='text-center' href="{% url 'users:Profile' %}">
                                <button class="btn btn-secondary" type="button">Update your profiles</button>
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-6 col-md-6 col-sm-6 ">
                    <div class="card">
                        <img class="card-img-top  img-responsive" src="{% static 'BlogApp/Images/notebook.jpg' %}" alt="Card image cap">
                        <div class="card-body">
                            <h5 class="card-title">Chapter</h5>
                            <p class="card-text">Click here to Create a new Chapter</p>
                            <div class="text-center">
                                <a href="{% url 'BlogApp:Post-create' %}">
                                <button class="btn btn-secondary" type="button">Create new Chapter</button>
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-6 col-md-6 col-sm-6">
                    <div class="card">
                        <img class="card-img-top  img-responsive" src="{% static 'BlogApp/Images/reading.jpg'  %}" alt="Card image cap">
                        <div class="card-body">
                            <h5 class="card-title">Read other Chapters </h5>
                            <p class="card-text">Click here to see what other people have posted</p>
                            <div class="text-center">
                                <a href="{% url 'BlogApp:Blogs' %}">
                                <button class="btn btn-secondary" type="button">Click here</button>
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-6 col-md-6 col-sm-6 ">
                    <div class="card">
                        <img class="card-img-top img-responsive" src="{% static 'BlogApp/Images/books.jpg' %}" alt="Card image cap">
                        <div class="card-body">
                            <h5 class="card-title">Journals</h5>
                            <p class="card-text">Click here to see your own journal</p>
                            <div class="text-center">
                                <a href="{% url 'BlogApp:Index' %}">
                                <button class="btn btn-secondary" type="button">Go to your journal</button>
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>


        <div class="col-lg-8 col-md-12 col-sm-12 content-style">
            <div class="card rounded shadow shadow-sm">
                <div class="signup-form">
                    <div class="card-header">
                        <h2>Post Something New!</h2>
                        <p class="hint-text">Upload a new post</p>
                    </div>
                    <div class="card-body">
                        <form method="POST">
                            {% csrf_token %}
                            <fieldset class="form-group">
                                <legend class="border-border mb-4"> Post Something New!</legend>
                                {{form|crispy }}
                            </fieldset>
                            <div class="form-group">
                                <button type="submit" class="btn btn-outline-info">Create Post</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}